export const APP_CONFIG = {
  OLLAMA_DEFAULT_URL: 'http://127.0.0.1:11434',
  BACKEND_DEFAULT_PORT: 15920,
  BACKEND_STATUS_INTERVAL: 5000,
  SETTINGS_STATUS_INTERVAL: 10000,
  ORGANIZE_STATUS_INTERVAL: 5000,
  TOAST_DEFAULT_DURATION: 3000,
  SEARCH_DEBOUNCE_MS: 500,
  MODEL_PULL_COOLDOWN_MS: 2000,
  MODEL_SWITCH_DELAY_MS: 3000,
  FAKE_PROGRESS_INTERVAL: 500,
  FAKE_PROGRESS_MAX: 90,
  SIDEBAR_WIDTH: 200,
  SIDEBAR_COLLAPSED_WIDTH: 52,
  SHORTCUTS: {
    SEARCH: { key: 'k', label: '搜索' },
    NEW_MEMORY: { key: 'n', label: '新建记忆' },
    SETTINGS: { key: ',', label: '设置' },
    HELP: { key: '/', label: '快捷键帮助' }
  }
} as const
